repos:
  - repo: https://github.com/andrei-shabanski/poetry-plugin-sort
    rev: v0.2.1
    hooks:
      - id: poetry-sort

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
