services:
  redis:
    image: bitnami/redis:6.2
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
    restart: always
    volumes:
      - "redis-data:/data"

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD:-password}@redis:6379/
      - SECURITY_TRAILS_API_KEY=${SECURITY_TRAILS_API_KEY}
    command: arq app.arq.worker.ArqWorkerSettings
    restart: always
    depends_on:
      - redis

  certstream:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD:-password}@redis:6379/
    command: python -m app.scripts.certstream
    restart: always
    depends_on:
      - redis

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD:-password}@redis:6379/
      - PORT=${PORT:-8000}
    command: uvicorn --host 0.0.0.0 --port ${PORT:-8000} app.main:app
    restart: always
    depends_on:
      - redis

volumes:
  redis-data:
