version: "3.7"
services:
  redis:
    image: bitnami/redis:6.2
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    volumes:
      - "redis-data:/data"

  worker:
    build:
      context: ./
      dockerfile: worker.Dockerfile
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/
      - SECURITY_TRAILS_API_KEY=${SECURITY_TRAILS_API_KEY}
    restart: always
      - redis

  certstream:
    build:
      context: ./
      dockerfile: certstream.Dockerfile
    environment:
      - SECURITY_TRAILS_API_KEY=${SECURITY_TRAILS_API_KEY}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/
    restart: always
    depends_on:
      - redis

  backend:
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TESTING=False
      - DEBUG=False
      - SECURITY_TRAILS_API_KEY=${SECURITY_TRAILS_API_KEY}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/
    restart: always
    depends_on:
      - redis

volumes:
  redis-data:
