[tool.poetry]
name = "ayashige"
version = "0.1.0"
description = ""
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
aiofiles = "^0.7.00"
arq = "^0.22"
dataclasses-json = "^0.5.5"
fastapi = "^0.68.1"
fastapi-cache2 = {version = "0.1.3.4", extras = ["redis"]}
gunicorn = "^20.1.0"
httpx = "^0.19.0"
loguru = "^0.5.3"
pyhumps = "^3.0.2"
pyopenssl = "^20.0.1"
python-Levenshtein = "^0.12.2"
tld = "^0.12.6"
ujson = "^5.2.0"
uvicorn = {extras = ["standard"], version = "^0.15.0"}
websocket-client = "^1.2.1"

[tool.poetry.dev-dependencies]
asynctest = "^0.13.0"
autoflake = "^1.4"
autopep8 = "^1.5.7"
black = "^21.8b0"
coveralls = "^3.2.0"
flake8 = "^3.9.2"
isort = "^5.9.3"
mypy = "^0.910"
nest-asyncio = "^1.5.1"
pre-commit = "^2.14.1"
pytest = "^6.2.5"
pytest-asyncio = "^0.15.1"
pytest-black = "^0.3.12"
pytest-cov = "^2.12.1"
pytest-env = "^0.6.2"
pytest-mock = "^3.6.1"
pytest-parallel = "^0.1.0"
pytest-randomly = "^3.10.1"
pytest-sugar = "^0.9.4"
pytest-timeout = "^1.4.2"
pyupgrade = "^2.25.0"
respx = "^0.17.1"
vcrpy = "^4.1.1"
fakeredis = "^1.6.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
