name: Python CI

on: ["pull_request", "push"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: "redis/redis-stack:6.2.4-v2"
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        python-version: [3.11]
        poetry-version: [1.8.3]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python and Poetry
        uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: ${{matrix.python-version}}
          poetry-version: ${{matrix.poetry-version}}
      - name: Run tests
        env:
          REDIS_URL: redis://localhost:6379
        run: poetry run pytest -v --cov=app --cov-report=term-missing
      - name: Coveralls
        env:
          COVERALLS_PARALLEL: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run coveralls --service=github
  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
